import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { FlaskConical } from "lucide-react";
import { Providers } from "./providers";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kommint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
        >
          <nav className="h-14 shadow-sm w-screen">
            <Link className="px-4 flex items-center h-full" href="/">
              <span className="font-serif">kommint</span>
              <FlaskConical className="h-4 w-4 ml-2" />
            </Link>
          </nav>
          {children}
        </body>
      </html>
    </Providers>
  );
}
